[tools]
zig = "0.15.2"
mdbook = "0.4.40"
act = "latest"

[tasks.docs]
description = "Build mdBook documentation"
run = """
mdbook build docs
rm -rf zig-out/docs
mkdir -p zig-out/docs
cp -r docs/book/. zig-out/docs/
"""
[tasks.npm-ci-chart-demo]
description = "Install JS deps for chart demo"
dir = "examples/chart-demo/www"
run = "npm ci"
